apiVersion: v1
kind: Service
metadata:
  name: agorasoftadmin-backend
  namespace: agorasoftadmin
spec:
  selector:
    app: agorasoftadmin-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP